### ISSUE TITLE
Could not add Steam oven and Microwave Oven 

### ISSUE THREAD

**Issue by RobHomey** [timyboy12345/Miele-Homey#1]
I could add the dishwasher but when adding the Steam oven and Microwave oven the app says: No new devices found.

**Comment by timyboy12345** [comment]
@RobHomey the problem should be fixed with the latest update (0.1.3), if this is the case, could you close this issue? Otherwise, please share any errors you are experiencing in this issue.

**Comment by RobvandeGoor** [comment]
Hi Tim, thanks for the update, it works. I have added the other devices. There is one thing I have to take care of and that is that the Dutch language is mixed with English. As example: When a program is finished: Dutch: Klaar, English: Finished.
I have to figure out which words I can use for triggering a label in a flow.

**Comment by timyboy12345** [comment]
I forgot that these are used for triggers as well. This will probably change a last time in the coming days, as I want to show Dutch users the Dutch statuses, and English users the English statuses. But I may also include the `status_id`, as this is universal and will never change. I will post a update on the forum post when this change is live.

**Comment by RobvandeGoor** [comment]
Hi Tim, 

Great news. Thanks for the update. I will check the forum and will wait for the upcoming update. 

Kinds regards,
Rob
